pipeline:
  name: Python
  identifier: Python
  projectIdentifier: SteveAbegunde_Project
  orgIdentifier: Dapo_Org
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubdaposon1
        repoName: Hello_Jango
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.bootcampgkecluster
              namespace: payment-service-build
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run
                  identifier: Run
                  spec:
                    connectorRef: DockerDaposon1
                    image: python:3.10
                    shell: Sh
                    command: |
                      python -m pip install --upgrade pip==21.1.2
                      python -m pip install -r requirements.txt
                      python manage.py runserver 8000
